/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Product;
import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author tnaxy
 */
public class ViewPanel extends javax.swing.JPanel {

    /**
     * Creates new form ViewPanel
     */

    public ViewPanel(Product product) {
        initComponents();
        displayProduct(product);
        ImageIcon imgplay=new ImageIcon();
    }
    private void displayProduct(Product product){
        String productName=product.getName();
        NameTextField.setText(productName);
        
        String productBankAccountNumber=product.getBankAccountNumber();
        BankAccountNumberTextField.setText(productBankAccountNumber);
        
        String productBirthDate=product.getBirthDate();
        BirthDateTextField.setText(productBirthDate);
        
        String productLicenseNumber=product.getLicenseNumber();
        LicenseNumberTextField.setText(productLicenseNumber);
        
        String productTelephoneNumbers=product.getTelephoneNumbers();
        TelephoneNumbersTextField.setText(productTelephoneNumbers);
        
        String productFaxNumber=product.getFaxNumber();
        FaxNumberTextField.setText(productFaxNumber);
        
        String productEmailAddresses=product.getEmailAddresses();
        EmailAddressTextField.setText(productEmailAddresses);
        
        String productSocialSecurityNumber=product.getSocialSecurityNumber();
        SocialSecurityNumberTextField.setText(productSocialSecurityNumber);
        
        String productMedicalRecordNumber=product.getMedicalRecordNumber();
        MedicalRecordNumberTextField.setText(productMedicalRecordNumber);
        
        String productGeographicData=product.getGeographicData();
        GeographicDataTextField.setText(productGeographicData);
        
        String productLinkedin=product.getLinkedin();
        LinkedinTextField.setText(productLinkedin);
        
        String productInternetProtocolAddress=product.getInternetProtocolAddress();
        InternetProtocolAddressTextField.setText(productInternetProtocolAddress);
        
     
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        NameTextField = new javax.swing.JTextField();
        BankAccountNumberTextField = new javax.swing.JTextField();
        LicenseNumberTextField = new javax.swing.JTextField();
        InternetProtocolAddressTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        BirthDateTextField = new javax.swing.JTextField();
        TelephoneNumbersTextField = new javax.swing.JTextField();
        FaxNumberTextField = new javax.swing.JTextField();
        EmailAddressTextField = new javax.swing.JTextField();
        SocialSecurityNumberTextField = new javax.swing.JTextField();
        MedicalRecordNumberTextField = new javax.swing.JTextField();
        LinkedinTextField = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        GeographicDataTextField = new javax.swing.JTextField();

        jLabel1.setFont(new java.awt.Font("等线", 0, 24)); // NOI18N
        jLabel1.setText("View");
        jLabel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setPreferredSize(new java.awt.Dimension(1200, 800));

        jLabel2.setText("Name");

        jLabel3.setText("BankAccount");

        jLabel4.setText("License Number");

        jLabel5.setText("Internet Protocol Address");

        NameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("BirthDate");

        jLabel8.setText("Telephone Number");

        jLabel9.setText("Fax Number");

        jLabel10.setText("Email Address");

        jLabel11.setText("Social Security Number");

        jLabel12.setText("Medical Record Number");

        jLabel13.setText("GeographicData");

        BirthDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BirthDateTextFieldActionPerformed(evt);
            }
        });

        TelephoneNumbersTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TelephoneNumbersTextFieldActionPerformed(evt);
            }
        });

        FaxNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FaxNumberTextFieldActionPerformed(evt);
            }
        });

        EmailAddressTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailAddressTextFieldActionPerformed(evt);
            }
        });

        SocialSecurityNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocialSecurityNumberTextFieldActionPerformed(evt);
            }
        });

        MedicalRecordNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MedicalRecordNumberTextFieldActionPerformed(evt);
            }
        });

        LinkedinTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LinkedinTextFieldActionPerformed(evt);
            }
        });

        jLabel14.setText("Linkedin");

        GeographicDataTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GeographicDataTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel13)
                                .addComponent(jLabel7)
                                .addComponent(jLabel2)
                                .addComponent(jLabel10)
                                .addComponent(jLabel11)
                                .addComponent(jLabel12)
                                .addComponent(jLabel8)
                                .addComponent(jLabel9))
                            .addGap(0, 13, Short.MAX_VALUE)))
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel5))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(NameTextField)
                    .addComponent(LinkedinTextField)
                    .addComponent(MedicalRecordNumberTextField)
                    .addComponent(SocialSecurityNumberTextField)
                    .addComponent(EmailAddressTextField)
                    .addComponent(FaxNumberTextField)
                    .addComponent(TelephoneNumbersTextField)
                    .addComponent(BirthDateTextField)
                    .addComponent(GeographicDataTextField)
                    .addComponent(InternetProtocolAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 359, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LicenseNumberTextField)
                    .addComponent(BankAccountNumberTextField))
                .addGap(151, 151, 151))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(NameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(BirthDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TelephoneNumbersTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(FaxNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(3, 3, 3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(EmailAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(SocialSecurityNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(MedicalRecordNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LinkedinTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(GeographicDataTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BankAccountNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(LicenseNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InternetProtocolAddressTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addContainerGap(105, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(316, 316, 316)
                .addComponent(jLabel1)
                .addContainerGap(362, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 713, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(508, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addGap(48, 48, 48)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
                    .addGap(28, 28, 28)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void GeographicDataTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GeographicDataTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_GeographicDataTextFieldActionPerformed

    private void LinkedinTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LinkedinTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LinkedinTextFieldActionPerformed

    private void MedicalRecordNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MedicalRecordNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_MedicalRecordNumberTextFieldActionPerformed

    private void SocialSecurityNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SocialSecurityNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SocialSecurityNumberTextFieldActionPerformed

    private void EmailAddressTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailAddressTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailAddressTextFieldActionPerformed

    private void FaxNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FaxNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FaxNumberTextFieldActionPerformed

    private void TelephoneNumbersTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TelephoneNumbersTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TelephoneNumbersTextFieldActionPerformed

    private void BirthDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BirthDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BirthDateTextFieldActionPerformed

    private void NameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField BankAccountNumberTextField;
    private javax.swing.JTextField BirthDateTextField;
    private javax.swing.JTextField EmailAddressTextField;
    private javax.swing.JTextField FaxNumberTextField;
    private javax.swing.JTextField GeographicDataTextField;
    private javax.swing.JTextField InternetProtocolAddressTextField;
    private javax.swing.JTextField LicenseNumberTextField;
    private javax.swing.JTextField LinkedinTextField;
    private javax.swing.JTextField MedicalRecordNumberTextField;
    private javax.swing.JTextField NameTextField;
    private javax.swing.JTextField SocialSecurityNumberTextField;
    private javax.swing.JTextField TelephoneNumbersTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
