/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.DataReader;
import Business.StudentList;
import Business.TeacherList;
import Interface.AdministrativeRole.AdminWorkAreaJPanel;
import Interface.StudentRole.LoginStudent;
import java.awt.CardLayout;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JLabel;
import javax.swing.JOptionPane;

/**
 *
 * @author Hui Huang
 */
public class MainJFrame extends javax.swing.JFrame {
    private StudentList studentList;
    private TeacherList teacherList;
    public String StudentCSVPath="./StudentCSV.csv";
    public String TeacherCSVPath="./TeacherCSV.csv";
    DataReader StudentReader;
    DataReader TeacherReader;
    String[] StudentRow;

    public String getStudentCSVPath() {
        return StudentCSVPath;
    }

    public void setStudentCSVPath(String StudentCSVPath) {
        this.StudentCSVPath = StudentCSVPath;
    }

    public String getTeacherCSVPath() {
        return TeacherCSVPath;
    }

    public void setTeacherCSVPath(String TeacherCSVPath) {
        this.TeacherCSVPath = TeacherCSVPath;
    }
    String[] TeacherRow;

    /**
     * Creates new form MainJFrame
     */
    public MainJFrame() {
        initComponents();
        studentList = new StudentList();
        teacherList = new TeacherList();
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSplitPane2 = new javax.swing.JSplitPane();
        userProcessContainer = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        btnAdministrative = new javax.swing.JButton();
        btnStudentManager = new javax.swing.JButton();
        btnStudentCSV = new javax.swing.JButton();
        btnTeacherCSV = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        userProcessContainer.setLayout(new java.awt.CardLayout());

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 36)); // NOI18N
        jLabel1.setText("                         Day Care Center");
        userProcessContainer.add(jLabel1, "card2");

        jSplitPane2.setRightComponent(userProcessContainer);

        btnAdministrative.setText("Administrator");
        btnAdministrative.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAdministrativeActionPerformed(evt);
            }
        });

        btnStudentManager.setText("Student Manager");
        btnStudentManager.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentManagerActionPerformed(evt);
            }
        });

        btnStudentCSV.setText("Import StudentCSV");
        btnStudentCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnStudentCSVActionPerformed(evt);
            }
        });

        btnTeacherCSV.setText("Import TeacherCSV");
        btnTeacherCSV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTeacherCSVActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btnStudentManager)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnStudentCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdministrative)
                    .addComponent(btnTeacherCSV, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(133, 133, 133)
                .addComponent(btnAdministrative)
                .addGap(48, 48, 48)
                .addComponent(btnStudentManager)
                .addGap(60, 60, 60)
                .addComponent(btnStudentCSV)
                .addGap(18, 18, 18)
                .addComponent(btnTeacherCSV)
                .addContainerGap(109, Short.MAX_VALUE))
        );

        jSplitPane2.setLeftComponent(jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jSplitPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1027, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAdministrativeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdministrativeActionPerformed
   
    try {
        
// TODO add your handling code here:
       
        AdminWorkAreaJPanel awajp = new AdminWorkAreaJPanel(userProcessContainer, studentList, teacherList,StudentCSVPath,TeacherCSVPath);
        userProcessContainer.add("AdminWordAreaJPanel",awajp);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    } catch (IOException ex) {
        Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
    }
   
    }//GEN-LAST:event_btnAdministrativeActionPerformed

    private void btnStudentManagerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentManagerActionPerformed
        try {
            // TODO add your handling code here:
            LoginStudent lp = new LoginStudent(userProcessContainer, studentList,StudentCSVPath,TeacherCSVPath);
            userProcessContainer.add("LoginStudentJPanel",lp);
            CardLayout layout = (CardLayout)userProcessContainer.getLayout();
            layout.next(userProcessContainer);
        } catch (IOException ex) {
            Logger.getLogger(MainJFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnStudentManagerActionPerformed

    private void btnStudentCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnStudentCSVActionPerformed
        // TODO add your handling code here:
        
        JFileChooser CSVChooser= new JFileChooser();
        CSVChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES );  
        CSVChooser.showDialog(new JLabel(), "choose");  
        
        File a=CSVChooser.getSelectedFile(); 
        setStudentCSVPath(a.getAbsolutePath());
        System.out.println(StudentCSVPath);
        JOptionPane.showMessageDialog(null,"Browse the StudentCSV Successfully ");
    }//GEN-LAST:event_btnStudentCSVActionPerformed

    private void btnTeacherCSVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTeacherCSVActionPerformed
        // TODO add your handling code here:
        JFileChooser CSVChooser= new JFileChooser();
        CSVChooser.setFileSelectionMode(JFileChooser.FILES_AND_DIRECTORIES );  
        CSVChooser.showDialog(new JLabel(), "choose");  
        
        File a=CSVChooser.getSelectedFile(); 
        setTeacherCSVPath(a.getAbsolutePath());
        System.out.println(TeacherCSVPath);
        JOptionPane.showMessageDialog(null,"Browse the TeacherCSV Successfully ");
    }//GEN-LAST:event_btnTeacherCSVActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdministrative;
    private javax.swing.JButton btnStudentCSV;
    private javax.swing.JButton btnStudentManager;
    private javax.swing.JButton btnTeacherCSV;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JPanel userProcessContainer;
    // End of variables declaration//GEN-END:variables
}
