/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.ShopModel;
import Business.Enterprise.ShopModel.ShopType;
import Business.Network.Network;
import Business.Role.CustomerRole;
import Business.Role.Role;
import Business.UserAccount.CustomerAccount;
import Business.UserAccount.UserAccount;
import UserInterface.LoginJFrame;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.DefaultListCellRenderer;
import javax.swing.DefaultListModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingConstants;


/**
 *
 * @author Hui Huang
 */
public class CustomerMainJPanel extends javax.swing.JPanel {

        private EcoSystem system;
        private JPanel container;
        private UserAccount account;
        private JFrame frame;        
        private CustomerAccount customerAccount;
        private Role role;     
        private ShopModel.ShopType type;
    /**
     * Creates new form CustomerMainJPanel
     */
    public CustomerMainJPanel(EcoSystem system, JPanel container, UserAccount account, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
//        this.account = account;
        this.customerAccount = (CustomerAccount) account;
        this.frame = frame; 
                
        //更新窗口的用户名username
        lblUsername.setText(customerAccount.getCustomer().getName());
        
        //给network city传入值
        cbChooseNetwork.removeAllItems();
        ArrayList<Network> networks = system.getNetworkList();
        for(Network network : networks) {
        cbChooseNetwork.addItem(network.getCity());
        }
        
        //给service type传入值，选cargo delivery 还是 pickup service
        cbChooseService.removeAllItems();
        
        
        cbChooseService.addItem(ShopType.CargoDelivery);
        cbChooseService.addItem(ShopType.PickupService);
        
    
        //btnNext.setEnabled(false);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblUsername = new javax.swing.JLabel();
        btnMyAccount = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        btnNext = new javax.swing.JButton();
        cbChooseNetwork = new javax.swing.JComboBox();
        cbChooseService = new javax.swing.JComboBox();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        lblUsername.setFont(new java.awt.Font("Lucida Grande", 3, 14)); // NOI18N
        lblUsername.setForeground(java.awt.Color.darkGray);
        lblUsername.setText("<Username> ");

        btnMyAccount.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnMyAccount.setText("My Account");
        btnMyAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMyAccountActionPerformed(evt);
            }
        });

        btnLogout.setFont(new java.awt.Font("Lucida Grande", 0, 14)); // NOI18N
        btnLogout.setText("Log out");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        btnNext.setFont(new java.awt.Font("Lucida Grande", 0, 16)); // NOI18N
        btnNext.setText("Continue >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        cbChooseNetwork.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbChooseNetwork.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChooseNetworkItemStateChanged(evt);
            }
        });
        cbChooseNetwork.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseNetworkActionPerformed(evt);
            }
        });

        cbChooseService.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbChooseService.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbChooseServiceItemStateChanged(evt);
            }
        });
        cbChooseService.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbChooseServiceActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel2.setText("Choose Network");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        jLabel3.setText("Choose Service");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 1, 24)); // NOI18N
        jLabel1.setText("Customer   Window");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(198, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(90, 90, 90)
                        .addComponent(lblUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLogout, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMyAccount, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(89, 89, 89)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbChooseNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbChooseService, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnNext))
                        .addGap(262, 262, 262))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMyAccount)
                    .addComponent(lblUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnLogout)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChooseNetwork, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbChooseService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(40, 40, 40)
                .addComponent(btnNext)
                .addContainerGap(190, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void cbChooseNetworkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseNetworkActionPerformed
        // TODO add your handling code here:     
    }//GEN-LAST:event_cbChooseNetworkActionPerformed

    private void btnMyAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMyAccountActionPerformed
        // TODO add your handling code here:
        CustomerAccountInfoJPanel caijp = new CustomerAccountInfoJPanel(this.system, this.container, this.customerAccount, this.frame, new CustomerRole());
        this.container.add(caijp);
        CardLayout layout = (CardLayout) this.container.getLayout();        
        layout.next(this.container);
        
//        CustomerProfileJPanel panel = new CustomerProfileJPanel(this.system, this.container, this.customerAccount, this.frame, new CustomerRole());
//        this.container.add(panel);
//        CardLayout layout = (CardLayout) this.container.getLayout();
//        layout.next(this.container);
    }//GEN-LAST:event_btnMyAccountActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        this.frame.dispose();//dispose()方法关闭窗体会释放该窗体的占用的部分资源。
        System.out.println(system.getNetworkList().size());
        
        LoginJFrame lf = new LoginJFrame();        
        lf.setLocationRelativeTo(null);//如果组件当前未显示或者 c 为 null，则此窗口将置于屏幕的中央。
        lf.setVisible(true);//setVisible方法仅仅隐藏窗体，而dispose方法是关闭窗体，并释放一部分资源
    }//GEN-LAST:event_btnLogoutActionPerformed

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        if(cbChooseNetwork.getSelectedItem() != null){
            String netname = cbChooseNetwork.getSelectedItem().toString();
            
            ShopType type = (ShopType) cbChooseService.getSelectedItem();
            ChooseCompanyJPanel ccjp = new ChooseCompanyJPanel(system, netname, this.container, this.customerAccount, type, this.frame);
            this.container.add(ccjp);
            CardLayout layout = (CardLayout) this.container.getLayout();
            layout.next(this.container);
            
        }else{
            JOptionPane.showMessageDialog(null, "Please select a network!");
        }
//        Network network = (Network)cbChooseNetwork.getSelectedItem();
//        ShopType type = (ShopType)cbChooseService.getSelectedItem();
//        CardLayout layout = (CardLayout) this.container.getLayout();
//        ChooseCompanyJPanel ccjp = new ChooseCompanyJPanel(system, network, container, customerAccount, type, frame);
//        this.container.add(ccjp);
//        layout.next(this.container);
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void cbChooseServiceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbChooseServiceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbChooseServiceActionPerformed

    private void cbChooseNetworkItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChooseNetworkItemStateChanged
        // TODO add your handling code here:
        //给network ComboBox 传入值
//        DefaultListCellRenderer renderer = (DefaultListCellRenderer) typeList.getCellRenderer();
        
        
        
        
    }//GEN-LAST:event_cbChooseNetworkItemStateChanged

    private void cbChooseServiceItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbChooseServiceItemStateChanged
        // TODO add your handling code here:
        //给和service ComboBox 传入值
//         DefaultListCellRenderer renderer = (DefaultListCellRenderer) typeList.getCellRenderer();
//        renderer.setHorizontalAlignment(SwingConstants.CENTER);
//        DefaultListModel<ShopType> model = new DefaultListModel<>();
//        for (ShopType type : ShopType.values()) {
//            model.addElement(type);
//        }
//        typeList.setModel(model);
//        goButton.setEnabled(false);
    }//GEN-LAST:event_cbChooseServiceItemStateChanged
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnMyAccount;
    private javax.swing.JButton btnNext;
    private javax.swing.JComboBox cbChooseNetwork;
    private javax.swing.JComboBox cbChooseService;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblUsername;
    // End of variables declaration//GEN-END:variables
}
