/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.CustomerRole;

import Business.EcoSystem;
import Business.Enterprise.CargoDeliveryCompany.CargoDelivery;
import Business.Enterprise.PickupServiceCompany.PickupService;
import Business.Enterprise.ShopModel;
import static Business.Enterprise.ShopModel.ShopType.CargoDelivery;
import static Business.Enterprise.ShopModel.ShopType.PickupService;
import Business.Organization.Organization;
import Business.UserAccount.CustomerAccount;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Hui Huang
 */
public class OrderDetailJPanel extends javax.swing.JPanel {

        private EcoSystem system;
        private JPanel container;
        private Organization organization;
        private CustomerAccount account;
        private JFrame frame;
    /**
     * Creates new form DriverNeedsJPanel
     */
    public OrderDetailJPanel(EcoSystem system, JPanel container, CargoDelivery organization, ShopModel.ShopType type, CustomerAccount account, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.organization = organization;
        this.account = account;
        this.frame = frame;
        
//        lblCompany.setText(organization.getId());
        
        if (type == CargoDelivery){
            //reference: https://www.uhaul.com/Truck-Rentals/
            cbCarType.removeAllItems();
            cbCarType.addItem("Cargo vans($20)");
            cbCarType.addItem("10' truck($25)");
            cbCarType.addItem("15' truck($30)");
            cbCarType.addItem("20' truck($35)");
            cbCarType.addItem("26' truck($40)");
            
            cbDistance.removeAllItems();
            cbDistance.addItem("< 10 miles ($20)");
            cbDistance.addItem("10 - 30 miles ($40)");
            cbDistance.addItem("31 - 60 miles ($60)");
            cbDistance.addItem("> 60 miles ($90)");
        }
            
            
        if (type == PickupService){
            cbCarType.removeAllItems();
            cbCarType.addItem("< 4 people($20)");
            cbCarType.addItem("5 - 7 people($30)");
            cbCarType.addItem("8 - 20 people($40)");
            cbCarType.addItem("21 - 60 people($60)");
            
            cbDistance.removeAllItems();
             cbDistance.addItem("< 10 miles ($20)");
            cbDistance.addItem("10 - 30 miles ($40)");
            cbDistance.addItem("31 - 60 miles ($60)");
            cbDistance.addItem("> 60 miles ($90)");
            
        }
    }
 public OrderDetailJPanel(EcoSystem system, JPanel container, PickupService organization, ShopModel.ShopType type, CustomerAccount account, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.organization = organization;
        this.account = account;
        this.frame = frame;
        
      //  lblCompany.setText(organization.getId());
        
        if (type == CargoDelivery){
            //reference: https://www.uhaul.com/Truck-Rentals/
            cbCarType.removeAllItems();
            cbCarType.addItem("Cargo vans($20)");
            cbCarType.addItem("10' truck($25)");
            cbCarType.addItem("15' truck($30)");
            cbCarType.addItem("20' truck($35)");
            cbCarType.addItem("26' truck($40)");
            
            cbDistance.removeAllItems();
            cbDistance.addItem("< 10 miles ($20)");
            cbDistance.addItem("10 - 30 miles ($40)");
            cbDistance.addItem("31 - 60 miles ($60)");
            cbDistance.addItem("> 60 miles ($90)");
        }
            
            
        if (type == PickupService){
            cbCarType.removeAllItems();
            cbCarType.addItem("< 4 people($20)");
            cbCarType.addItem("5 - 7 people($30)");
            cbCarType.addItem("8 - 20 people($40)");
            cbCarType.addItem("21 - 60 people($60)");
            
            cbDistance.removeAllItems();
             cbDistance.addItem("< 10 miles ($20)");
            cbDistance.addItem("10 - 30 miles ($40)");
            cbDistance.addItem("31 - 60 miles ($60)");
            cbDistance.addItem("> 60 miles ($90)");
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCarType = new javax.swing.JLabel();
        lblDistance = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        txtAppointedTime = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        btnTime = new javax.swing.JLabel();
        txtLocation = new javax.swing.JTextField();
        lblDestination = new javax.swing.JLabel();
        txtDestination = new javax.swing.JTextField();
        cbCarType = new javax.swing.JComboBox();
        cbDistance = new javax.swing.JComboBox();
        lblCompany = new javax.swing.JLabel();
        lblShowTotalPrice = new javax.swing.JLabel();

        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setText("Next >>");

        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setText("<< Back");

        lblCarType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCarType.setText("Car Type");

        lblDistance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDistance.setText("Distance");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalPrice.setText("Total Price");

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLocation.setText("Location");

        btnTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTime.setText("Time");

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDestination.setText("Destination");

        cbCarType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        cbDistance.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        lblCompany.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCompany.setText("<Company Name>");

        lblShowTotalPrice.setText("<Total Price>");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 576, Short.MAX_VALUE)
                .addComponent(txtAppointedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(212, 212, 212))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(btnBack)
                        .addGap(227, 227, 227)
                        .addComponent(lblCompany))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(423, 423, 423)
                        .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(157, 157, 157))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(228, 228, 228)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnTime)
                            .addComponent(lblCarType)
                            .addComponent(lblDistance)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblLocation)
                            .addComponent(lblDestination))
                        .addGap(244, 244, 244)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblShowTotalPrice))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(lblCompany))
                .addGap(68, 68, 68)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarType)
                    .addComponent(cbCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistance)
                    .addComponent(cbDistance, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPrice)
                    .addComponent(lblShowTotalPrice))
                .addGap(31, 31, 31)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTime)
                    .addComponent(txtAppointedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLocation)
                    .addComponent(txtLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDestination)
                    .addComponent(txtDestination, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 520, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel btnTime;
    private javax.swing.JComboBox cbCarType;
    private javax.swing.JComboBox cbDistance;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblCarType;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblShowTotalPrice;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtAppointedTime;
    private javax.swing.JTextField txtDestination;
    private javax.swing.JTextField txtLocation;
    // End of variables declaration//GEN-END:variables
}
