/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.CargoDelivery;

import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Employee.Employee;
import Business.Enterprise.CargoDelivery.CargoCartype;

import Business.Enterprise.CargoDelivery.CargoDelivery;
import Business.Enterprise.Enterprise;
import Business.Network.Network;
import Business.UserAccount.CargoManagerAccount;
import Business.UserAccount.DriverAccount;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.DriveRequest;
import Business.WorkQueue.OrderRequest;
import Business.WorkQueue.WorkRequest;
import UserInterface.LoginJFrame;
import java.awt.CardLayout;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.Random;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;


/**
 *
 * @author junxiang
 */
public class CargoDeliveryMainJPanel extends javax.swing.JPanel {
        private EcoSystem system;
        private JPanel container;
        private UserAccount account;
        private CargoManagerAccount cargoManagerAccount;
        private JFrame frame; 
        private Network network;
        private Enterprise enterprise;
        private CargoDelivery cargoDelivery;
        private Employee employee;
    /**
     * Creates new form CargoDeliveryMainJPanel
     */
    public CargoDeliveryMainJPanel(EcoSystem system, JPanel container, Network net, Enterprise en, UserAccount userAccount, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.network = net;
        this.enterprise = en;
        this.cargoDelivery = (CargoDelivery)en;       
        this.cargoManagerAccount = (CargoManagerAccount) account;
//        this.employee = this.cargoManagerAccount.getCargoManager();//null pointer exception
        this.frame = frame; 
        this.cargoDelivery.setItems(new ArrayList<>());
        this.system.setcargo(this.cargoDelivery);
        setOverviewInfo();//XJ
        populateServiceTable();//XJ
        populateDriver();
        populateDriverTable();
        populateEmployee();
        populatableReview();
        txtAddress.setText(this.cargoDelivery.getAddress());
        txtcpnName.setText(this.cargoDelivery.getCompanyName());
        txtCpnPhone.setText(this.cargoDelivery.getPhone());
        txtDescription.setText(this.cargoDelivery.getDescription());
    }
    
    //initialize the overview panel using data from system db4o --XJ
    private void setOverviewInfo() {
        nameLabel.setText(cargoDelivery.getCompanyName());
        txtcpnName.setText(cargoDelivery.getCompanyName());
        txtCpnPhone.setText(cargoDelivery.getPhone());
        txtAddress.setText(cargoDelivery.getAddress());
        txtDescription.setText(cargoDelivery.getDescription());
    }
    //initialize the manage services panel using data from system db4o --XJ
    public void populateServiceTable() {
        DefaultTableModel dtm = (DefaultTableModel)serviceTable.getModel();
        dtm.setRowCount(0);
        for (CargoCartype col : this.system.getCargoCartypeList()) {
            System.out.println(col.toString());
            Object row[] = new Object[2];
            row[0] = col;
            row[1] = col.getPrice();
            dtm.addRow(row);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        logoutButton = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        servicePanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        serviceTable = new javax.swing.JTable();
        createServButton = new javax.swing.JButton();
        removeServButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        createPanel = new javax.swing.JPanel();
        employeePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tableEmployee = new javax.swing.JTable();
        createEplButton = new javax.swing.JButton();
        wokrPanel = new javax.swing.JPanel();
        removeEplButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        tableDriveRequest = new javax.swing.JTable();
        jScrollPane6 = new javax.swing.JScrollPane();
        tableDriver = new javax.swing.JTable();
        btnSendRequest = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tblReview = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        firstnameTextField = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        lastnameTextField = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        phoneTextField1 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        emailTextField = new javax.swing.JTextField();
        savePrfButton = new javax.swing.JButton();
        cancelPrfButton = new javax.swing.JButton();
        overviewPanel = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtcpnName = new javax.swing.JTextField();
        txtCpnPhone = new javax.swing.JTextField();
        saveButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescription = new javax.swing.JTextArea();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtAddress = new javax.swing.JTextArea();
        cancelButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 23, 21));
        jLabel1.setText("Cargo Delivery Company Manager Work Area");

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(161, 23, 21));
        jLabel2.setText("Welcome,");

        nameLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        nameLabel.setForeground(new java.awt.Color(161, 23, 21));
        nameLabel.setText("<Name>");

        logoutButton.setBackground(new java.awt.Color(255, 255, 255));
        logoutButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        logoutButton.setForeground(new java.awt.Color(161, 23, 21));
        logoutButton.setText("Logout");
        logoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutButtonActionPerformed(evt);
            }
        });

        jTabbedPane1.setBackground(new java.awt.Color(255, 255, 255));
        jTabbedPane1.setForeground(new java.awt.Color(161, 23, 21));

        servicePanel.setBackground(new java.awt.Color(255, 255, 255));

        serviceTable.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        serviceTable.setForeground(new java.awt.Color(161, 23, 21));
        serviceTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Car Type", "Price($/mile)"
            }
        ));
        jScrollPane3.setViewportView(serviceTable);

        createServButton.setBackground(new java.awt.Color(255, 255, 255));
        createServButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createServButton.setForeground(new java.awt.Color(161, 23, 21));
        createServButton.setText("Create Service");
        createServButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createServButtonActionPerformed(evt);
            }
        });

        removeServButton.setBackground(new java.awt.Color(255, 255, 255));
        removeServButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removeServButton.setForeground(new java.awt.Color(161, 23, 21));
        removeServButton.setText("Remove Service");
        removeServButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeServButtonActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(161, 23, 21));
        jLabel7.setText("Service List:");

        createPanel.setBackground(new java.awt.Color(242, 242, 242));
        createPanel.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout servicePanelLayout = new javax.swing.GroupLayout(servicePanel);
        servicePanel.setLayout(servicePanelLayout);
        servicePanelLayout.setHorizontalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addGap(79, 79, 79)
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(servicePanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(servicePanelLayout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(removeServButton)
                                    .addComponent(createServButton, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(servicePanelLayout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addComponent(createPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jLabel7))
                .addContainerGap(39, Short.MAX_VALUE))
        );
        servicePanelLayout.setVerticalGroup(
            servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(servicePanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(servicePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 287, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(servicePanelLayout.createSequentialGroup()
                        .addComponent(createServButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(removeServButton)
                        .addGap(18, 18, 18)
                        .addComponent(createPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Services", servicePanel);

        employeePanel.setBackground(new java.awt.Color(255, 255, 255));
        employeePanel.setForeground(new java.awt.Color(242, 242, 242));

        tableEmployee.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        tableEmployee.setForeground(new java.awt.Color(161, 23, 21));
        tableEmployee.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Username", "Name", "Phone", "Email"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(tableEmployee);

        createEplButton.setBackground(new java.awt.Color(255, 255, 255));
        createEplButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        createEplButton.setForeground(new java.awt.Color(161, 23, 21));
        createEplButton.setText("Create Employee");
        createEplButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createEplButtonActionPerformed(evt);
            }
        });

        wokrPanel.setBackground(new java.awt.Color(239, 239, 239));
        wokrPanel.setLayout(new java.awt.CardLayout());

        removeEplButton.setBackground(new java.awt.Color(255, 255, 255));
        removeEplButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        removeEplButton.setForeground(new java.awt.Color(161, 23, 21));
        removeEplButton.setText("Remove Employee");
        removeEplButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removeEplButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout employeePanelLayout = new javax.swing.GroupLayout(employeePanel);
        employeePanel.setLayout(employeePanelLayout);
        employeePanelLayout.setHorizontalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 460, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(wokrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(createEplButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(removeEplButton, javax.swing.GroupLayout.Alignment.LEADING))))
                .addContainerGap(26, Short.MAX_VALUE))
        );
        employeePanelLayout.setVerticalGroup(
            employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(employeePanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(employeePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(employeePanelLayout.createSequentialGroup()
                        .addComponent(createEplButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(removeEplButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(wokrPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 371, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Employees", employeePanel);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        tableDriveRequest.setForeground(new java.awt.Color(161, 23, 21));
        tableDriveRequest.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Order ID", "Order Date", "Order Status", "Time", "Location", "Destination", "Distance", "Expected Pay"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableDriveRequest.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableDriveRequestMouseClicked(evt);
            }
        });
        jScrollPane5.setViewportView(tableDriveRequest);

        tableDriver.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Driver Name"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane6.setViewportView(tableDriver);

        btnSendRequest.setText("Send Request");
        btnSendRequest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendRequestActionPerformed(evt);
            }
        });

        jButton2.setText("Cancel");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 588, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnSendRequest, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(99, 99, 99)
                        .addComponent(btnSendRequest)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)))
                .addContainerGap(115, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Manage Orders", jPanel1);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        tblReview.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Date", "Customer", "Score", "Comment"
            }
        ));
        jScrollPane7.setViewportView(tblReview);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(183, Short.MAX_VALUE)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(184, 184, 184))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Reviews", jPanel2);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(161, 23, 21));
        jLabel8.setText("First Name:");

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(161, 23, 21));
        jLabel9.setText("Last Name:");

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(161, 23, 21));
        jLabel10.setText("Phone:");

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(161, 23, 21));
        jLabel11.setText("Email:");

        savePrfButton.setBackground(new java.awt.Color(255, 255, 255));
        savePrfButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        savePrfButton.setForeground(new java.awt.Color(161, 23, 21));
        savePrfButton.setText("Save");
        savePrfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                savePrfButtonActionPerformed(evt);
            }
        });

        cancelPrfButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelPrfButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelPrfButton.setForeground(new java.awt.Color(161, 23, 21));
        cancelPrfButton.setText("Cancel");
        cancelPrfButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelPrfButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addComponent(savePrfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(550, 550, 550))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(235, 235, 235)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81)
                        .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(107, 107, 107)
                                .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(cancelPrfButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lastnameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(emailTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)))))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(82, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addComponent(firstnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel9)
                    .addComponent(lastnameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(emailTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(savePrfButton)
                    .addComponent(cancelPrfButton))
                .addGap(109, 109, 109))
        );

        jTabbedPane1.addTab("My profile", jPanel3);

        overviewPanel.setBackground(new java.awt.Color(255, 255, 255));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(161, 23, 21));
        jLabel3.setText("Company Name: ");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(161, 23, 21));
        jLabel4.setText("Telephone: ");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(161, 23, 21));
        jLabel5.setText("Address: ");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(161, 23, 21));
        jLabel6.setText("Brief Introduction: ");

        saveButton.setBackground(new java.awt.Color(255, 255, 255));
        saveButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        saveButton.setForeground(new java.awt.Color(161, 23, 21));
        saveButton.setText("Save");
        saveButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveButtonActionPerformed(evt);
            }
        });

        txtDescription.setColumns(20);
        txtDescription.setRows(5);
        jScrollPane1.setViewportView(txtDescription);

        txtAddress.setColumns(20);
        txtAddress.setRows(5);
        jScrollPane2.setViewportView(txtAddress);

        cancelButton.setBackground(new java.awt.Color(255, 255, 255));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancelButton.setForeground(new java.awt.Color(161, 23, 21));
        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout overviewPanelLayout = new javax.swing.GroupLayout(overviewPanel);
        overviewPanel.setLayout(overviewPanelLayout);
        overviewPanelLayout.setHorizontalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addGap(62, 62, 62)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtCpnPhone)
                    .addComponent(txtcpnName)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 175, Short.MAX_VALUE))
                .addGap(118, 118, 118)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(overviewPanelLayout.createSequentialGroup()
                            .addComponent(saveButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 267, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        overviewPanelLayout.setVerticalGroup(
            overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(overviewPanelLayout.createSequentialGroup()
                .addContainerGap(90, Short.MAX_VALUE)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtcpnName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addGap(39, 39, 39)
                .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(saveButton)
                            .addComponent(cancelButton)))
                    .addGroup(overviewPanelLayout.createSequentialGroup()
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtCpnPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(40, 40, 40)
                        .addGroup(overviewPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(53, 53, 53))
        );

        jTabbedPane1.addTab("Overview", overviewPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(logoutButton)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(104, 104, 104)
                        .addComponent(jLabel2)
                        .addGap(30, 30, 30)
                        .addComponent(nameLabel)))
                .addGap(125, 125, 125))
            .addGroup(layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 938, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(198, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addComponent(logoutButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 473, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(67, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void logoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutButtonActionPerformed
        LoginJFrame lf = new LoginJFrame();
        this.frame.dispose();
        lf.setLocationRelativeTo(null);
        lf.setVisible(true);
    }//GEN-LAST:event_logoutButtonActionPerformed

    private void saveButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveButtonActionPerformed
        // TODO add your handling code here:
        if (!txtcpnName.getText().equals("") && !txtCpnPhone.getText().equals("") 
                && !txtAddress.getText().equals("") && !txtDescription.getText().equals("")) {
            
            cargoDelivery.setCompanyName(txtcpnName.getText());
            cargoDelivery.setPhone(txtCpnPhone.getText());
            cargoDelivery.setAddress(txtAddress.getText());
            cargoDelivery.setDescription(txtDescription.getText());
            
            
        } else {
            JOptionPane.showMessageDialog(null, "Information can't be empty");
            return;
        }
        
        setOverviewInfo();
        
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_saveButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        // TODO add your handling code here:
        setOverviewInfo();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void createServButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createServButtonActionPerformed
        // TODO add your handling code here:
        ServiceCreateJPanel scjp = new ServiceCreateJPanel(system, this, createPanel, cargoDelivery);
        this.createPanel.add(scjp);
        CardLayout layout = (CardLayout) createPanel.getLayout();
        layout.next(createPanel);
    }//GEN-LAST:event_createServButtonActionPerformed

    private void createEplButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createEplButtonActionPerformed
        // TODO add your handling code here:
        this.wokrPanel.removeAll();
        EmployeeCreateJPanel ep = new EmployeeCreateJPanel(this.system, this, wokrPanel, cargoDelivery);
        this.wokrPanel.add(ep);
        CardLayout layout = (CardLayout) wokrPanel.getLayout();
        layout.next(this.wokrPanel);
    }//GEN-LAST:event_createEplButtonActionPerformed

    private void removeServButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeServButtonActionPerformed
        // TODO add your handling code here:
        int index = serviceTable.getSelectedRow();
        system.getCargoCartypeList().remove(serviceTable.getValueAt(index, 0));
        
        populateServiceTable();
    }//GEN-LAST:event_removeServButtonActionPerformed

    private void savePrfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_savePrfButtonActionPerformed
        // TODO add your handling code here:
        if (!emailTextField.getText().equals("") && !firstnameTextField.getText().equals("")
                && !lastnameTextField.getText().equals("") && !phoneTextField1.getText().equals("")) {
              this.employee.setFirstName(firstnameTextField.getText());
              this.employee.setLastName(lastnameTextField.getText());
              this.employee.setPhone(phoneTextField1.getText());
              this.employee.setEmail(emailTextField.getText());

        } else {
            JOptionPane.showMessageDialog(null, "Information can't be empty");
            return;
        }
          
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_savePrfButtonActionPerformed

    private void cancelPrfButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelPrfButtonActionPerformed
        // TODO add your handling code here:
            int index = tableEmployee.getSelectedRow();
            this.cargoDelivery.getEmployeeDir().getEmployeeList().remove(tableEmployee.getValueAt(index, 0));
            populateEmployee();
    }//GEN-LAST:event_cancelPrfButtonActionPerformed

    private void tableDriveRequestMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableDriveRequestMouseClicked
        // TODO add your handling code here:

    }//GEN-LAST:event_tableDriveRequestMouseClicked

    private void btnSendRequestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendRequestActionPerformed
       int requestindex = tableDriveRequest.getSelectedRow();
        OrderRequest dr = (OrderRequest)tableDriveRequest.getValueAt(requestindex, 1);
        int driverindex = tableDriver.getSelectedRow();
        DriverAccount drvac = (DriverAccount)tableDriver.getValueAt(driverindex, 0);
//        LinkedList<WorkRequest> tempList = new LinkedList<>();
//        for(WorkRequest wr : drvac.getWorkQueue().getWorkRequestList()){
//            tempList.add(wr);
//        }
//        tempList.add(dr);
        DriveRequest tempdr = new DriveRequest(enterprise, account, dr);
        LinkedList<DriveRequest> templist = new LinkedList<>();
        
        
        templist.add(tempdr);
        drvac.setDriveRequestDirectory(templist);
        JOptionPane.showMessageDialog(null, "The request has been sent to the selected Driver");
        //drvac.getWorkQueue().getWorkRequestList().add(dr);
        //system.getUserAccountDirectory().getUserAccountList().add(drvac);
        DB4OUtil.getInstance().storeSystem(system);
    }//GEN-LAST:event_btnSendRequestActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void removeEplButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removeEplButtonActionPerformed
        // TODO add your handling code here:
        
       int index = tableEmployee.getSelectedRow();
            this.cargoDelivery.getEmployeeDir().getEmployeeList().remove(tableEmployee.getValueAt(index, 0));
            populateEmployee();
    }//GEN-LAST:event_removeEplButtonActionPerformed

 public void populateEmployee(){
        DefaultTableModel dtm =(DefaultTableModel)tableEmployee.getModel();
        dtm.setRowCount(0);
        
        for(Employee usa:this.cargoDelivery.getEmployeeDir().getEmployeeList()){
            Object row[] = new Object[4];
            row[0] = usa;
            row[1] = usa.getFirstName();
            row[2] = usa.getPhone();
            row[3] = usa.getEmail();
            dtm.addRow(row);  
        }  
    }
    
    public void populateDriver(){
        DefaultTableModel dtm = (DefaultTableModel)tableDriveRequest.getModel();
        dtm.setRowCount(0);
        String test = "123123";
        double testdouble = 6.666;
        //this.cargoDelivery.getWorkQueue().getWorkRequestList().add(new DriveRequest(enterprise, account,new OrderRequest(enterprise, account, test, test, testdouble, testdouble, test)) );
        for(OrderRequest dr: this.cargoDelivery.getOrderList()){
            
            
                Object row[] = new Object[8];
               
                
                row[0] = dr.getId();
                row[1] = dr;
                row[2] = dr.getStatus();
                row[3] = dr.getTime();
                row[4] = dr.getLocation();
                row[5] = dr.getDestination();
                row[6] = dr.getDistance();
                row[7] = dr.getTotalPrice();
                dtm.addRow(row);
            
        }
        
       
    }
    public void populateDriverTable(){
        DefaultTableModel dt = (DefaultTableModel)tableDriver.getModel();
        dt.setRowCount(0);
        
        for(UserAccount ua:network.getUserAccountDirectory().getUserAccountList()){
            
            if(ua instanceof DriverAccount){
                Object row[] = new Object[2];
                DriverAccount tempua = (DriverAccount)ua;
                row[0] = tempua;
               // row[1] = ;
                dt.addRow(row);
            }
        }
        
    }
    public void populatableReview(){
        DefaultTableModel dtm = (DefaultTableModel)tblReview.getModel();
        dtm.setRowCount(0);
        
        for(OrderRequest or:this.cargoDelivery.getOrderList()){
            Object row[] = new Object[4];
            row[0] = or.getReview();
            row[1] ="Customer 1";
            Random r = new Random();
            
            row[2] = r.nextInt(3)+7;
            row[3] = or.getRemark();
            dtm.addRow(row);
        }               
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSendRequest;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton cancelPrfButton;
    private javax.swing.JButton createEplButton;
    private javax.swing.JPanel createPanel;
    private javax.swing.JButton createServButton;
    private javax.swing.JTextField emailTextField;
    private javax.swing.JPanel employeePanel;
    private javax.swing.JTextField firstnameTextField;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField lastnameTextField;
    private javax.swing.JButton logoutButton;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JPanel overviewPanel;
    private javax.swing.JTextField phoneTextField1;
    private javax.swing.JButton removeEplButton;
    private javax.swing.JButton removeServButton;
    private javax.swing.JButton saveButton;
    private javax.swing.JButton savePrfButton;
    private javax.swing.JPanel servicePanel;
    private javax.swing.JTable serviceTable;
    private javax.swing.JTable tableDriveRequest;
    private javax.swing.JTable tableDriver;
    private javax.swing.JTable tableEmployee;
    private javax.swing.JTable tblReview;
    private javax.swing.JTextArea txtAddress;
    private javax.swing.JTextField txtCpnPhone;
    private javax.swing.JTextArea txtDescription;
    private javax.swing.JTextField txtcpnName;
    private javax.swing.JPanel wokrPanel;
    // End of variables declaration//GEN-END:variables

    
}
