/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface.AdministrativeRole;

import Business.DataReader;
import Business.Immunization;
import Business.Student;
import Business.StudentList;
import Business.Teacher;
import Business.TeacherList;
import java.awt.CardLayout;
import javax.swing.JPanel;
import java.io.*;
import java.util.*;

/**
 *
 * @author Hui Huang
 */
public class AdminWorkAreaJPanel extends javax.swing.JPanel {
    private JPanel userProcessContainer;
    private StudentList studentList;
    private TeacherList teacherList;
    DataReader StudentReader;
    DataReader TeacherReader;
    String[] StudentRow;
    String[] TeacherRow;
    public final String STUDENT_CSV_PATH ="./StudentCSV.csv";
    public final String TEACHER_CSV_PATH = "./TeacherCSV.csv";
    /**
     * Creates new form AdminWorkAreaJPanel
     */
    public AdminWorkAreaJPanel(JPanel userProcessContainer,StudentList studentList,TeacherList teacherList) throws FileNotFoundException, IOException {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.studentList=studentList;
        this.teacherList=teacherList;
        StudentReader = new DataReader(STUDENT_CSV_PATH);
        TeacherReader = new DataReader(TEACHER_CSV_PATH);
        
        while((StudentRow = StudentReader.getNextRow()) != null){
            
          Student student = new Student();
          student.setAge(Integer.valueOf(StudentRow[1]));
          student.setParentsName(StudentRow[2]);
          student.setName(StudentRow[0]);
          student.setRegistrationDate(StudentRow[3]);
          for(int i =0;4*i+7<StudentRow.length;i++){
          Immunization imu = new Immunization();
          if(!StudentRow[4*i+4].equals(""))imu.setImmunizationName(StudentRow[4*i+4]);
          if(!StudentRow[4*i+5].equals(""))imu.setType(StudentRow[4*i+5]);
          if(!StudentRow[4*i+6].equals(""))imu.setPeriod(StudentRow[4*i+6]);
          if(!StudentRow[4*i+7].equals(""))imu.setTime(StudentRow[4*i+7]);
          student.getImmunizationList().getImmunizationList().add(imu);
          }
          this.studentList.getStudentList().add(student);
    }
        while((TeacherRow=TeacherReader.getNextRow())!=null){
            Teacher teacher = new Teacher();
            teacher.setAge(Integer.valueOf(TeacherRow[1]));
            teacher.setName(TeacherRow[0]);
            this.teacherList.getTeacherList().add(teacher);
        }
    }
 public AdminWorkAreaJPanel(JPanel userProcessContainer,StudentList studentList,TeacherList teacherList,String StudentCSV, String TeacherCSV) throws FileNotFoundException, IOException {
        initComponents();
        this.userProcessContainer=userProcessContainer;
        this.studentList=studentList;
        this.teacherList=teacherList;
        StudentReader = new DataReader(StudentCSV);
        TeacherReader = new DataReader(TeacherCSV);
        
        while((StudentRow = StudentReader.getNextRow()) != null){
            
          Student student = new Student();
          student.setAge(Integer.valueOf(StudentRow[1]));
          student.setParentsName(StudentRow[2]);
          student.setName(StudentRow[0]);
          student.setRegistrationDate(StudentRow[3]);
          for(int i =0;4*i+7<StudentRow.length;i++){
          Immunization imu = new Immunization();
          if(!StudentRow[4*i+4].equals(""))imu.setImmunizationName(StudentRow[4*i+4]);
          if(!StudentRow[4*i+5].equals(""))imu.setType(StudentRow[4*i+5]);
          if(!StudentRow[4*i+6].equals(""))imu.setPeriod(StudentRow[4*i+6]);
          if(!StudentRow[4*i+7].equals(""))imu.setTime(StudentRow[4*i+7]);
          student.getImmunizationList().getImmunizationList().add(imu);
          }
          this.studentList.getStudentList().add(student);
    }
        while((TeacherRow=TeacherReader.getNextRow())!=null){
            Teacher teacher = new Teacher();
            teacher.setAge(Integer.valueOf(TeacherRow[1]));
            teacher.setName(TeacherRow[0]);
            this.teacherList.getTeacherList().add(teacher);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        btnManageStudent = new javax.swing.JButton();
        btnManageTeacher = new javax.swing.JButton();
        btnback = new javax.swing.JButton();

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("My Work Area -Aminstrative Role");

        btnManageStudent.setText("Manage Student >>");
        btnManageStudent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageStudentActionPerformed(evt);
            }
        });

        btnManageTeacher.setText("Manage Teacher >>");
        btnManageTeacher.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTeacherActionPerformed(evt);
            }
        });

        btnback.setText("Back");
        btnback.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbackActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(btnback)
                        .addGap(171, 171, 171)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(380, 380, 380)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnManageTeacher)
                            .addComponent(btnManageStudent))))
                .addContainerGap(311, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnback))
                .addGap(97, 97, 97)
                .addComponent(btnManageStudent)
                .addGap(108, 108, 108)
                .addComponent(btnManageTeacher)
                .addContainerGap(160, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnManageStudentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageStudentActionPerformed
        // TODO add your handling code here:
        ManageStudent panel = new ManageStudent(userProcessContainer, studentList,teacherList);
        userProcessContainer.add("ManageStudentAdministrative", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageStudentActionPerformed

    private void btnManageTeacherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTeacherActionPerformed
        // TODO add your handling code here:
        ManageTeacher panel = new ManageTeacher(userProcessContainer, teacherList,studentList);
        userProcessContainer.add("ManageTeacherAdministrative", panel);
        CardLayout layout = (CardLayout)userProcessContainer.getLayout();
        layout.next(userProcessContainer);
    }//GEN-LAST:event_btnManageTeacherActionPerformed

    private void btnbackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbackActionPerformed
        // TODO add your handling code here:
        userProcessContainer.remove(this);
        CardLayout layout = (CardLayout) userProcessContainer.getLayout();
        layout.previous(userProcessContainer);
    }//GEN-LAST:event_btnbackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageStudent;
    private javax.swing.JButton btnManageTeacher;
    private javax.swing.JButton btnback;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
