/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;


import Business.EcoSystem;
import Business.Enterprise.CargoDelivery.CargoDelivery;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PickupService.PickupService;
import Business.UserAccount.CustomerAccount;
import Business.WorkQueue.OrderRequest;
import java.awt.CardLayout;
import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Hui Huang
 */
public class OrderDetailJPanel extends javax.swing.JPanel {

        private EcoSystem system;
        private JPanel container;     
        private CustomerAccount account;
        private JFrame frame;
        private CargoDelivery cargoDelivery;
        private PickupService pickupService;
        private boolean pivot;
        double priceDirectory[][] = {{0,7.7,1.6,3.6,4.5,8.1},
                                     {7.7,0,7.1,11.2,5.2,2.8},
                                     {1.6,7.1,0,4.7,5.0,6.6},
                                     {3.6,11.2,4.7,0,9.9,11.2},
                                     {4.5,5.2,5.0,9.9,0,3.5},
                                     {8.1,2.8,6.6,11.2,3.5,0}
        
        
        };
        double totalpriceforshow;
   
    /**
     * Creates new form DriverNeedsJPanel
     */
   
       
    public void populatable(){
        DefaultTableModel dtm = (DefaultTableModel) LocationTable.getModel();
        DefaultTableModel dtmd = (DefaultTableModel) DestinationTable.getModel();
        dtm.setRowCount(0);
        dtmd.setRowCount(0);
        Object row[] = new Object[1];
        row[0] = "NEU";
        dtm.addRow(row);
        dtmd.addRow(row);
        row[0] = "Malden";
        dtm.addRow(row);
        dtmd.addRow(row);
        row[0] = "ChinaTown";
        dtm.addRow(row);
        dtmd.addRow(row);
        row[0] = "Dorchester";
        dtm.addRow(row);
        dtmd.addRow(row);
        row[0] = "Harvard";
        dtm.addRow(row);
        dtmd.addRow(row);
        row[0] = "Medford";
        dtm.addRow(row);
        dtmd.addRow(row); 
    }
    public OrderDetailJPanel(EcoSystem system, JPanel container, CustomerAccount account, JFrame frame,Enterprise enterprise) {
        initComponents();
        this.system = system;
        this.container = container;
       
        this.account = account;
        this.frame = frame;
        if(enterprise instanceof CargoDelivery){this.cargoDelivery = (CargoDelivery)enterprise;
         this.pivot = true;}
        
        else {this.pickupService = (PickupService)enterprise;
         this.pivot = false;
        }
       
        cbCarType.removeAllItems();
        cbCarType.addItem("9' cargo van($2)");
        cbCarType.addItem("10' truck($2.5)");
        cbCarType.addItem("15' truck($3)");
        cbCarType.addItem("17' truck($4)");
        populatable();
    }
 

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        btnNext = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        lblCarType = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        txtAppointedTime = new javax.swing.JTextField();
        lblLocation = new javax.swing.JLabel();
        btnTime = new javax.swing.JLabel();
        lblDestination = new javax.swing.JLabel();
        cbCarType = new javax.swing.JComboBox();
        lblShowTotalPrice = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        LocationTextField = new javax.swing.JTextField();
        DistanceTextJField = new javax.swing.JTextField();
        DestinationField = new javax.swing.JTextField();
        jScrollPane4 = new javax.swing.JScrollPane();
        DestinationTable = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        LocationTable = new javax.swing.JTable();
        lblImage = new javax.swing.JLabel();
        btnshowdetails = new javax.swing.JButton();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 600));

        btnNext.setBackground(new java.awt.Color(255, 255, 255));
        btnNext.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnNext.setForeground(new java.awt.Color(161, 23, 21));
        btnNext.setText("Next >>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(161, 23, 21));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCarType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCarType.setForeground(new java.awt.Color(161, 23, 21));
        lblCarType.setText("Car Type");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(161, 23, 21));
        lblTotalPrice.setText("Total Price");

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(161, 23, 21));
        lblLocation.setText("From");

        btnTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnTime.setForeground(new java.awt.Color(161, 23, 21));
        btnTime.setText("Time");

        lblDestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDestination.setForeground(new java.awt.Color(161, 23, 21));
        lblDestination.setText("To");

        cbCarType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbCarType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbCarTypeActionPerformed(evt);
            }
        });

        lblShowTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowTotalPrice.setForeground(new java.awt.Color(161, 23, 21));
        lblShowTotalPrice.setText("<Total Price>");
        lblShowTotalPrice.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblShowTotalPriceMouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 23, 21));
        jLabel1.setText("Or Input the Location, Destination and Distance by yourself");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(161, 23, 21));
        jLabel3.setText("Location");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(161, 23, 21));
        jLabel4.setText("Destination");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(161, 23, 21));
        jLabel5.setText("Distance");

        DestinationTable.setForeground(new java.awt.Color(161, 23, 21));
        DestinationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Destination"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        DestinationTable.setColumnSelectionAllowed(true);
        jScrollPane4.setViewportView(DestinationTable);
        DestinationTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        LocationTable.setForeground(new java.awt.Color(161, 23, 21));
        LocationTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null},
                {null},
                {null},
                {null}
            },
            new String [] {
                "Location"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(LocationTable);
        LocationTable.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);

        lblImage.setText("<LableImage>");

        btnshowdetails.setBackground(new java.awt.Color(255, 255, 255));
        btnshowdetails.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnshowdetails.setForeground(new java.awt.Color(161, 23, 21));
        btnshowdetails.setText("Show Details");
        btnshowdetails.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnshowdetailsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(97, 97, 97)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTime)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(2, 2, 2)
                            .addComponent(btnBack)
                            .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(jPanel1Layout.createSequentialGroup()
                                                .addGap(77, 77, 77)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addComponent(btnshowdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(40, 40, 40)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                .addComponent(lblCarType)
                                                .addComponent(jLabel5))
                                            .addGap(771, 771, 771)))
                                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel1)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblLocation))
                                            .addGap(68, 68, 68)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(lblDestination)
                                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jLabel4)
                                                .addComponent(lblTotalPrice))
                                            .addGap(105, 105, 105)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(DestinationField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(LocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(DistanceTextJField, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(cbCarType, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(txtAppointedTime, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(lblShowTotalPrice))))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGap(108, 108, 108)))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnBack)
                        .addGap(58, 58, 58)
                        .addComponent(lblImage, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(lblLocation))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(lblDestination)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(jLabel1)
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(LocationTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(DestinationField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addComponent(DistanceTextJField, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5)))))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbCarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblCarType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTime)
                    .addComponent(txtAppointedTime, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnshowdetails, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblShowTotalPrice)
                    .addComponent(lblTotalPrice))
                .addGap(101, 101, 101))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1224, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 664, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        // TODO add your handling code here:
        double distancemiles=0;
//        set order.totoalPrice, carType, distance, time, location, destination
        double priceCarType = 0;
        double priceDistance = 0;
        String carType = null;
        String distance = null;
        String destination="" ;
        String location="";
        if (cbCarType.getSelectedItem().equals("9' cargo van($20)")) 
            {priceCarType = 20; carType = "CargoVan";}
        if (cbCarType.getSelectedItem().equals("10' truck($30)")) 
            {priceCarType = 30; carType = "Truck10";}
        if (cbCarType.getSelectedItem().equals("15' truck($40)"))
            {priceCarType = 40; carType = "Truck15";}
        if (cbCarType.getSelectedItem().equals("17' truck($50)"))
            {priceCarType = 50; carType = "Truck17";}
        if (cbCarType.getSelectedItem().equals("Economy for 4 people($20)")) 
            {priceCarType = 20; carType = "Economy4";}
        if (cbCarType.getSelectedItem().equals("Extra Seats for 6 people($30)")) 
            {priceCarType = 30; carType = "Extra6";}
        if (cbCarType.getSelectedItem().equals("Luxury for 4 people($30)")) 
            {priceCarType = 30; carType = "Luxury4";}
        
//        if(cbDistance.getSelectedItem().equals("< 10 miles ($20)")) 
//            {priceDistance = 20; distance = "< 10 miles";}
//        if(cbDistance.getSelectedItem().equals("10 - 30 miles ($40)"))
//             {priceDistance = 40; distance = "10 - 30 miles";}
//        if(cbDistance.getSelectedItem().equals("31 - 60 miles ($60)")) 
//            {priceDistance = 60; distance = "31 - 60 miles miles";}
//        if(cbDistance.getSelectedItem().equals("> 60 miles ($90)"))
//            {priceDistance = 90; distance = "> 60 miles miles";}
        int locationindex = LocationTable.getSelectedRow();
        int destinationindex = DestinationTable.getSelectedRow();
        if (locationindex>=0&&destinationindex>=0)    
        {    
            location = LocationTable.getValueAt(locationindex, 0).toString();
             destination = DestinationTable.getValueAt(destinationindex, 0).toString();
             distancemiles= priceDirectory[locationindex][destinationindex];
        }else if(locationindex>=0&&destinationindex<0){
            location = LocationTable.getValueAt(locationindex, 0).toString();
            destination = DestinationField.getText();
            distancemiles = Double.valueOf(DistanceTextJField.getText());
            
        }else if (locationindex<0&&destinationindex>=0){
            distancemiles = Double.valueOf(DistanceTextJField.getText());
            location = LocationTextField.getText();
            destination = DestinationTable.getValueAt(destinationindex, 0).toString();
        } 
      double orderprice=0;
       
       
         
//         
//        if (distance < 10 && distance > 0) {
//            BigDecimal bd = new BigDecimal(item.getPrice() * 20);
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else if(distance < 30){
//            BigDecimal bd = new BigDecimal(item.getPrice() * 40);  
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else if (distance < 60) {
//            BigDecimal bd = new BigDecimal(item.getPrice() * 60); 
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else{
//            BigDecimal bd = new BigDecimal(item.getPrice());  
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }
                          
       
    
        if (pivot) {
            switch( cbCarType.getSelectedIndex()){
           case 0:
               orderprice = 2*distancemiles;
               break;
           case 1:
               orderprice = 2.5*distancemiles;
               break;
           case 2:
               orderprice = 3*distancemiles;
               break;
           case 3:
               orderprice = 3.5*distancemiles;
               break;
           case 4:
               orderprice = 4*distancemiles;
               break;
                 
       }
        }else{
            switch( cbCarType.getSelectedIndex()){
           case 0:
               orderprice = 5*distancemiles;
               break;
           case 1:
               orderprice = 6*distancemiles;
               break;
           case 2:
               orderprice = 7*distancemiles;
               break;
           case 3:
               orderprice = 8*distancemiles;
               break;
        }   
        }
        OrderRequest order = new OrderRequest((cargoDelivery==null)?pickupService:cargoDelivery,account,location,destination,distancemiles,orderprice,carType);
        order.setTime(txtAppointedTime.getText());
        totalpriceforshow =orderprice;
            System.out.println("Interface.CustomerRole.OrderDetailJPanel.btnNextActionPerformed()");
            
        if(pivot){
            PlaceOrderPanel pop = new PlaceOrderPanel(system, container, cargoDelivery, account, order, frame);
            this.container.add(pop);
            CardLayout layout = (CardLayout)this.container.getLayout();
            layout.next(this.container);
            System.out.println("cargodelivery");
        }else{
            PlaceOrderPanel pop = new PlaceOrderPanel(system, container, pickupService, account, order, frame);
            this.container.add(pop);
            CardLayout layout = (CardLayout)this.container.getLayout();
            layout.next(this.container);
            System.out.println("pickupservice");
        }
        
    }//GEN-LAST:event_btnNextActionPerformed

    private void lblShowTotalPriceMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblShowTotalPriceMouseClicked
        // TODO add your handling code here:
        String destination="" ;
        String location="";
        double distancemiles=0;
        int locationindex = LocationTable.getSelectedRow();
        int destinationindex = DestinationTable.getSelectedRow();
        if (locationindex>=0&&destinationindex>=0)    
        {    
            location = LocationTable.getValueAt(locationindex, 0).toString();
             destination = DestinationTable.getValueAt(destinationindex, 0).toString();
             distancemiles= priceDirectory[locationindex][destinationindex];
        }else if(locationindex>=0&&destinationindex<0){
            location = LocationTable.getValueAt(locationindex, 0).toString();
            destination = DestinationField.getText();
            distancemiles = Double.valueOf(DistanceTextJField.getText());
            
        }else if (locationindex<0&&destinationindex>=0){
            distancemiles = Double.valueOf(DistanceTextJField.getText());
            location = LocationTextField.getText();
            destination = DestinationTable.getValueAt(destinationindex, 0).toString();
        } 
      double orderprice=0;
       
       
         
//         
//        if (distance < 10 && distance > 0) {
//            BigDecimal bd = new BigDecimal(item.getPrice() * 20);
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else if(distance < 30){
//            BigDecimal bd = new BigDecimal(item.getPrice() * 40);  
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else if (distance < 60) {
//            BigDecimal bd = new BigDecimal(item.getPrice() * 60); 
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else{
//            BigDecimal bd = new BigDecimal(item.getPrice());  
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }
                          
       
    
        if (pivot) {
            switch( cbCarType.getSelectedIndex()){
           case 0:
               orderprice = 2*distancemiles;
               break;
           case 1:
               orderprice = 2.5*distancemiles;
               break;
           case 2:
               orderprice = 3*distancemiles;
               break;
           case 3:
               orderprice = 3.5*distancemiles;
               break;
           case 4:
               orderprice = 4*distancemiles;
               break;
                 
       }
        }else{
            switch( cbCarType.getSelectedIndex()){
           case 0:
               orderprice = 5*distancemiles;
               break;
           case 1:
               orderprice = 6*distancemiles;
               break;
           case 2:
               orderprice = 7*distancemiles;
               break;
           case 3:
               orderprice = 8*distancemiles;
               break;
        }   
        }
        lblShowTotalPrice.setText(String.valueOf(orderprice));
    }//GEN-LAST:event_lblShowTotalPriceMouseClicked

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnshowdetailsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnshowdetailsActionPerformed
        // TODO add your handling code here:
        String destination="" ;
        String location="";
        double distancemiles=0;
        int locationindex = LocationTable.getSelectedRow();
        int destinationindex = DestinationTable.getSelectedRow();
        if (locationindex>=0&&destinationindex>=0)    
        {    
            location = LocationTable.getValueAt(locationindex, 0).toString();
             destination = DestinationTable.getValueAt(destinationindex, 0).toString();
             distancemiles= priceDirectory[locationindex][destinationindex];
        }else if(locationindex>=0&&destinationindex<0){
            location = LocationTable.getValueAt(locationindex, 0).toString();
            destination = DestinationField.getText();
            distancemiles = Double.valueOf(DistanceTextJField.getText());
            
        }else if (locationindex<0&&destinationindex>=0){
            distancemiles = Double.valueOf(DistanceTextJField.getText());
            location = LocationTextField.getText();
            destination = DestinationTable.getValueAt(destinationindex, 0).toString();
        } 
      double orderprice=0;
       
       
         
//         
//        if (distance < 10 && distance > 0) {
//            BigDecimal bd = new BigDecimal(item.getPrice() * 20);
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else if(distance < 30){
//            BigDecimal bd = new BigDecimal(item.getPrice() * 40);  
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else if (distance < 60) {
//            BigDecimal bd = new BigDecimal(item.getPrice() * 60); 
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }else{
//            BigDecimal bd = new BigDecimal(item.getPrice());  
//            this.totalPrice = bd.setScale(2, BigDecimal.ROUND_HALF_UP).doubleValue();//四舍五入，2.35变成2.4
//        }
                          
       
    
        if (pivot) {
            switch( cbCarType.getSelectedIndex()){
           case 0:
               orderprice = 2*distancemiles;
               break;
           case 1:
               orderprice = 2.5*distancemiles;
               break;
           case 2:
               orderprice = 3*distancemiles;
               break;
           case 3:
               orderprice = 3.5*distancemiles;
               break;
           case 4:
               orderprice = 4*distancemiles;
               break;
                 
       }
        }else{
            switch( cbCarType.getSelectedIndex()){
           case 0:
               orderprice = 5*distancemiles;
               break;
           case 1:
               orderprice = 6*distancemiles;
               break;
           case 2:
               orderprice = 7*distancemiles;
               break;
           case 3:
               orderprice = 8*distancemiles;
               break;
        }   
        }
        lblShowTotalPrice.setText(String.valueOf(orderprice));
        showImage();
    }//GEN-LAST:event_btnshowdetailsActionPerformed

    private void cbCarTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbCarTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbCarTypeActionPerformed
    private void showImage() {
        ImageIcon image = null;
        StringBuffer s = new StringBuffer("images/");
        StringBuffer s2 = new StringBuffer("images/");
        int locationindex = LocationTable.getSelectedRow();
        int destinationindex = DestinationTable.getSelectedRow();
        if(locationindex!=destinationindex){
            s.append(locationindex).append("-").append(destinationindex).append(".jpg");
            s2.append(destinationindex).append("-").append(locationindex).append(".jpg");
            image = (locationindex<destinationindex)?new ImageIcon(s.toString()):new ImageIcon(s2.toString());
        }else image = new ImageIcon("images/0-0.jpg");
        
        image.setImage(image.getImage().getScaledInstance(350, 350, Image.SCALE_DEFAULT));
        lblImage.setText("");
        lblImage.setIcon(image);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField DestinationField;
    private javax.swing.JTable DestinationTable;
    private javax.swing.JTextField DistanceTextJField;
    private javax.swing.JTable LocationTable;
    private javax.swing.JTextField LocationTextField;
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnNext;
    private javax.swing.JLabel btnTime;
    private javax.swing.JButton btnshowdetails;
    private javax.swing.JComboBox cbCarType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JLabel lblCarType;
    private javax.swing.JLabel lblDestination;
    private javax.swing.JLabel lblImage;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblShowTotalPrice;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtAppointedTime;
    // End of variables declaration//GEN-END:variables
}
