
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;


import Business.DB4OUtil.DB4OUtil;
import Business.EcoSystem;
import Business.Enterprise.CargoDelivery.CargoDelivery;
import Business.Enterprise.Enterprise;
import Business.Enterprise.PickupService.PickupService;

import Business.UserAccount.CustomerAccount;
import Business.WorkQueue.OrderRequest;
import java.awt.CardLayout;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import java.util.*;

/**
 *
 * @author Hui Huang
 */
public class PlaceOrderPanel extends javax.swing.JPanel {
    
        private EcoSystem system;
        private JPanel container;
        private OrderRequest orderRequest;
        private CustomerAccount account;
        private JFrame frame;
        private CargoDelivery cargoDelivery=null;
        public PickupService pickupService=null;
       
        
 public PlaceOrderPanel(EcoSystem system, JPanel container, CargoDelivery enterprise, CustomerAccount account,OrderRequest orderRequest, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.cargoDelivery = enterprise;
        this.account = account;
        this.frame = frame;
        this.orderRequest = orderRequest;
        
        lblShowCarType.setText(orderRequest.getCarType());
        lblShowDistance.setText(String.valueOf(orderRequest.getDistance()));
        lblShowLocation.setText(orderRequest.getLocation());
        lblShowDestination.setText(orderRequest.getDestination());
        lblShowTime.setText(orderRequest.getTime());
        lblShowTotalPrice.setText(String.valueOf(orderRequest.getTotalPrice()));
        //lblCompany
       
       
    }
 public PlaceOrderPanel(EcoSystem system, JPanel container, PickupService enterprise, CustomerAccount account,OrderRequest orderRequest, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.pickupService = enterprise;
        this.account = account;
        this.frame = frame;
        this.orderRequest = orderRequest;
        
        lblShowCarType.setText(orderRequest.getCarType());
        lblShowDistance.setText(String.valueOf(orderRequest.getDistance()));
        lblShowLocation.setText(orderRequest.getLocation());
        lblShowDestination.setText(orderRequest.getDestination());
        lblShowTime.setText(orderRequest.getTime());
        lblShowTotalPrice.setText(String.valueOf(orderRequest.getTotalPrice()));
        //lblCompany
       
       
    }
    /**
     * Creates new form PlaceOrderJPanel
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblShowCarType = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblDistance = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblRemark = new javax.swing.JLabel();
        txtRemark = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblShowDestination = new javax.swing.JLabel();
        lblShowLocation = new javax.swing.JLabel();
        lblShowTime = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblShowDistance = new javax.swing.JLabel();
        lblShowTotalPrice = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblCarType = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        lblShowCarType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowCarType.setForeground(new java.awt.Color(161, 23, 21));
        lblShowCarType.setText("<Car Type>");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(161, 23, 21));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblDistance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDistance.setForeground(new java.awt.Color(161, 23, 21));
        lblDistance.setText("Distance");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(161, 23, 21));
        lblTotalPrice.setText("Total Price");

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(161, 23, 21));
        lblCustomerName.setText("Customer Name");

        lblRemark.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRemark.setForeground(new java.awt.Color(161, 23, 21));
        lblRemark.setText("Remark");

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(161, 23, 21));
        lblPhone.setText("Phone");

        lblShowDestination.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowDestination.setForeground(new java.awt.Color(161, 23, 21));
        lblShowDestination.setText("<Destination>");

        lblShowLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowLocation.setForeground(new java.awt.Color(161, 23, 21));
        lblShowLocation.setText("<Location>");

        lblShowTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowTime.setForeground(new java.awt.Color(161, 23, 21));
        lblShowTime.setText("<Time>");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(161, 23, 21));
        lblTime.setText("Time");

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(161, 23, 21));
        lblLocation.setText("Location");

        lblShowDistance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowDistance.setForeground(new java.awt.Color(161, 23, 21));
        lblShowDistance.setText("<Distance>");

        lblShowTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblShowTotalPrice.setForeground(new java.awt.Color(161, 23, 21));
        lblShowTotalPrice.setText("<Total Price>");

        btnPlaceOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(161, 23, 21));
        btnPlaceOrder.setText("Place Order >>");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 23, 21));
        jLabel1.setText("Destination");

        lblCarType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCarType.setForeground(new java.awt.Color(161, 23, 21));
        lblCarType.setText("Car Type");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDistance)
                            .addComponent(lblTotalPrice)
                            .addComponent(lblCustomerName)
                            .addComponent(lblRemark)
                            .addComponent(lblCarType))
                        .addGap(73, 73, 73)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblShowTotalPrice)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(txtRemark)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(lblShowCarType)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(lblTime))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(lblShowDistance)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 251, Short.MAX_VALUE)
                                                .addComponent(lblLocation))
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addGap(0, 0, Short.MAX_VALUE)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                    .addComponent(lblPhone)
                                                    .addComponent(jLabel1))))
                                        .addGap(162, 162, 162)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblShowTime)
                                            .addComponent(lblShowLocation)
                                            .addComponent(lblShowDestination))
                                        .addGap(8, 8, 8)))
                                .addGap(175, 175, 175))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnBack)
                        .addContainerGap())))
            .addGroup(layout.createSequentialGroup()
                .addGap(403, 403, 403)
                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(btnBack)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblShowTime, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblShowCarType)
                        .addComponent(lblCarType)
                        .addComponent(lblTime)))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistance)
                    .addComponent(lblShowDistance)
                    .addComponent(lblShowLocation)
                    .addComponent(lblLocation))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPrice)
                    .addComponent(lblShowTotalPrice)
                    .addComponent(jLabel1)
                    .addComponent(lblShowDestination))
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(93, 93, 93))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
            // TODO add your handling code here:
        this.orderRequest.setCustomerName(txtCustomerName.getText());
        this.orderRequest.setCustomerPhone(txtPhone.getText());
        this.orderRequest.setRemark(txtRemark.getText());
        
            
            if(cargoDelivery!=null){
                LinkedList<OrderRequest> templist = new LinkedList<>();
                
                templist.add(orderRequest);
                for(OrderRequest or:this.cargoDelivery.getOrderList()){
                    templist.add(or);
                }
                this.cargoDelivery.setOrderList(templist);
                //this.cargoDelivery.setProcessingOrderRequest(orderRequest);
                JOptionPane.showMessageDialog(null, "The request has been sent to CargoDelivery!");
                OrderConfirmationJPanel ocfJPanel= new OrderConfirmationJPanel(container,this.orderRequest,system,frame);
                this.container.add(ocfJPanel);
                CardLayout layout = (CardLayout)this.container.getLayout();
                layout.next(this.container);
            } else if(pickupService!=null){
                LinkedList<OrderRequest> templist = new LinkedList<>();
                
                templist.add(orderRequest);
//                for(OrderRequest or:this.pickupService.getOrderList()){
//                    templist.add(or);
//                }
                this.pickupService.setOrderList(templist);
                //this.cargoDelivery.setProcessingOrderRequest(orderRequest);
                JOptionPane.showMessageDialog(null, "The request has been sent to CargoDelivery!");
                OrderConfirmationJPanel ocfJPanel= new OrderConfirmationJPanel(container,this.orderRequest,system , frame);
                this.container.add(ocfJPanel);
                CardLayout layout = (CardLayout)this.container.getLayout();
                layout.next(this.container);
            } else{
                    JOptionPane.showMessageDialog(null, "Place Order Error!");}
//            else this.pickupService.getWorkQueue().getWorkRequestList().add(orderRequest);
            DB4OUtil.getInstance().storeSystem(system);
      
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarType;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JLabel lblShowCarType;
    private javax.swing.JLabel lblShowDestination;
    private javax.swing.JLabel lblShowDistance;
    private javax.swing.JLabel lblShowLocation;
    private javax.swing.JLabel lblShowTime;
    private javax.swing.JLabel lblShowTotalPrice;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRemark;
    // End of variables declaration//GEN-END:variables
}
