
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.Customer;


import Business.EcoSystem;
import Business.Enterprise.Enterprise;

import Business.UserAccount.CustomerAccount;
import Business.WorkQueue.OrderRequest;
import java.awt.CardLayout;
import javax.swing.JFrame;
import javax.swing.JPanel;

/**
 *
 * @author Hui Huang
 */
public class PlaceOrderPanel extends javax.swing.JPanel {
    
        private EcoSystem system;
        private JPanel container;
        private OrderRequest orderRequest;
        private CustomerAccount account;
        private JFrame frame;
        private Enterprise enterprise;
       
        
 public PlaceOrderPanel(EcoSystem system, JPanel container, Enterprise enterprise, CustomerAccount account,OrderRequest orderRequest, JFrame frame) {
        initComponents();
        this.system = system;
        this.container = container;
        this.enterprise = enterprise;
        this.account = account;
        this.frame = frame;
        this.orderRequest = orderRequest;
        
        lblCarType.setText(orderRequest.getCarType());
        lblShowDistance.setText(String.valueOf(orderRequest.getDistance()));
        lblShowLocation.setText(orderRequest.getLocation());
        lblShowDestination.setText(orderRequest.getDestination());
        lblShowTime.setText(orderRequest.getTime());
        lblShowTotalPrice.setText(String.valueOf(orderRequest.getTotalPrice()));
        //lblCompany
       
       
    }

    /**
     * Creates new form PlaceOrderJPanel
     */
   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblCompany = new javax.swing.JLabel();
        lblShowCarType = new javax.swing.JLabel();
        btnBack = new javax.swing.JButton();
        lblCarType = new javax.swing.JLabel();
        lblDistance = new javax.swing.JLabel();
        lblTotalPrice = new javax.swing.JLabel();
        lblCustomerName = new javax.swing.JLabel();
        lblRemark = new javax.swing.JLabel();
        txtRemark = new javax.swing.JTextField();
        txtCustomerName = new javax.swing.JTextField();
        lblPhone = new javax.swing.JLabel();
        txtPhone = new javax.swing.JTextField();
        lblShowDestination = new javax.swing.JLabel();
        lblShowLocation = new javax.swing.JLabel();
        lblShowTime = new javax.swing.JLabel();
        lblTime = new javax.swing.JLabel();
        lblLocation = new javax.swing.JLabel();
        lblShowDistance = new javax.swing.JLabel();
        lblShowTotalPrice = new javax.swing.JLabel();
        btnPlaceOrder = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(1200, 600));

        lblCompany.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lblCompany.setForeground(new java.awt.Color(161, 23, 21));
        lblCompany.setText("<Company Name>");

        lblShowCarType.setForeground(new java.awt.Color(161, 23, 21));
        lblShowCarType.setText("<Car Type>");

        btnBack.setBackground(new java.awt.Color(255, 255, 255));
        btnBack.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnBack.setForeground(new java.awt.Color(161, 23, 21));
        btnBack.setText("<< Back");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        lblCarType.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCarType.setForeground(new java.awt.Color(161, 23, 21));
        lblCarType.setText("Car Type");

        lblDistance.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblDistance.setForeground(new java.awt.Color(161, 23, 21));
        lblDistance.setText("Distance");

        lblTotalPrice.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTotalPrice.setForeground(new java.awt.Color(161, 23, 21));
        lblTotalPrice.setText("Total Price");

        lblCustomerName.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblCustomerName.setForeground(new java.awt.Color(161, 23, 21));
        lblCustomerName.setText("Customer Name");

        lblRemark.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblRemark.setForeground(new java.awt.Color(161, 23, 21));
        lblRemark.setText("Remark");

        lblPhone.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblPhone.setForeground(new java.awt.Color(161, 23, 21));
        lblPhone.setText("Phone");

        lblShowDestination.setForeground(new java.awt.Color(161, 23, 21));
        lblShowDestination.setText("<Destination>");

        lblShowLocation.setForeground(new java.awt.Color(161, 23, 21));
        lblShowLocation.setText("<Location>");

        lblShowTime.setForeground(new java.awt.Color(161, 23, 21));
        lblShowTime.setText("<Time>");

        lblTime.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblTime.setForeground(new java.awt.Color(161, 23, 21));
        lblTime.setText("Time");

        lblLocation.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        lblLocation.setForeground(new java.awt.Color(161, 23, 21));
        lblLocation.setText("Location");

        lblShowDistance.setForeground(new java.awt.Color(161, 23, 21));
        lblShowDistance.setText("<Distance>");

        lblShowTotalPrice.setForeground(new java.awt.Color(161, 23, 21));
        lblShowTotalPrice.setText("<Total Price>");

        btnPlaceOrder.setBackground(new java.awt.Color(255, 255, 255));
        btnPlaceOrder.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        btnPlaceOrder.setForeground(new java.awt.Color(161, 23, 21));
        btnPlaceOrder.setText("Place Order >>");
        btnPlaceOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlaceOrderActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(161, 23, 21));
        jLabel1.setText("Destination");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblRemark)
                    .addComponent(lblDistance)
                    .addComponent(lblCarType)
                    .addComponent(lblTotalPrice)
                    .addComponent(lblCustomerName))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 59, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblShowTotalPrice)
                                    .addComponent(lblShowCarType)
                                    .addComponent(lblShowDistance)
                                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPhone)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(lblTime)
                                        .addComponent(lblLocation)
                                        .addComponent(jLabel1)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblShowTime)
                                    .addComponent(lblShowLocation)
                                    .addComponent(lblShowDestination)
                                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(106, 106, 106))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(359, 359, 359)))
                .addGap(161, 161, 161))
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnBack)
                .addGap(265, 265, 265)
                .addComponent(lblCompany)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnBack)
                    .addComponent(lblCompany))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCarType)
                    .addComponent(lblShowCarType)
                    .addComponent(lblTime)
                    .addComponent(lblShowTime))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDistance)
                    .addComponent(lblShowDistance)
                    .addComponent(lblLocation)
                    .addComponent(lblShowLocation))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTotalPrice)
                    .addComponent(lblShowTotalPrice)
                    .addComponent(jLabel1)
                    .addComponent(lblShowDestination))
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblCustomerName)
                    .addComponent(txtCustomerName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblPhone)
                    .addComponent(txtPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(81, 81, 81))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(txtRemark, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)))
                .addComponent(btnPlaceOrder, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(297, 297, 297))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPlaceOrderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlaceOrderActionPerformed
            // TODO add your handling code here:
        this.orderRequest.setCustomerName(txtCustomerName.getText());
        this.orderRequest.setCustomerPhone(txtPhone.getText());
        this.orderRequest.setRemark(txtRemark.getText());
        OrderConfirmationJPanel ocfJPanel= new OrderConfirmationJPanel(container,this.orderRequest);
        this.container.add(ocfJPanel);
            CardLayout layout = (CardLayout)this.container.getLayout();
            layout.next(this.container);
      
    }//GEN-LAST:event_btnPlaceOrderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        container.remove(this);
        CardLayout layout = (CardLayout) container.getLayout();
        layout.previous(container);
    }//GEN-LAST:event_btnBackActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnPlaceOrder;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblCarType;
    private javax.swing.JLabel lblCompany;
    private javax.swing.JLabel lblCustomerName;
    private javax.swing.JLabel lblDistance;
    private javax.swing.JLabel lblLocation;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblRemark;
    private javax.swing.JLabel lblShowCarType;
    private javax.swing.JLabel lblShowDestination;
    private javax.swing.JLabel lblShowDistance;
    private javax.swing.JLabel lblShowLocation;
    private javax.swing.JLabel lblShowTime;
    private javax.swing.JLabel lblShowTotalPrice;
    private javax.swing.JLabel lblTime;
    private javax.swing.JLabel lblTotalPrice;
    private javax.swing.JTextField txtCustomerName;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtRemark;
    // End of variables declaration//GEN-END:variables
}
